version: '2'
services:

  minimal-brod-example-s:
    image: xofspades/minimal-brod-example:0.0.1
    container_name: minimal-brod-example-c
    build:
      context: .
      args:
        - mix_env=dev
    command: mix run --no-halt
    volumes:
      - ./resources:/resources
      - .:/app
      - ./config:/minimal_brod_example/config
    depends_on:
      - test-kafka-s
      - test-zk4kafka-s
    networks:
      - "test-n"

  test-kafka-s:
    image: confluentinc/cp-kafka:4.1.0
    container_name: test-kafka-c
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: test-zk4kafka-s:38272 # test-zk4kafka-s:38272
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.28.171:38222 # PLAINTEXT://test-kafka-s:38222
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      #KAFKA_COMPRESSION_TYPE: 'lz4'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'false'
      KAFKA_LOG_CLEANER_ENABLE: 'true'
      KAFKA_LOG_RETENTION_BYTES: 300000000000
      KAFKA_LOG_RETENTION_MS: 313360000000
      KAFKA_OFFSETS_RETENTION_MINUTES: 6912000
      KAFKA_MAX_CONNECTIONS_PER_IP: 100
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,state.change.logger=INFO"
      KAFKA_TOOLS_LOG4J_LOGLEVEL: INFO
      KAFKA_JMX_HOSTNAME: test-kafka-s #test-kafka-s
      KAFKA_JMX_PORT: 38229
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "100"
    depends_on:
      - test-zk4kafka-s
    networks:
      - "test-n"
    ports:
      - "38222:38222"
      - "38229:38229"
    volumes:
      - kafka-data-v:/var/lib/kafka/data

  test-zk4kafka-s:
    image: confluentinc/cp-zookeeper:4.1.0
    container_name: test-zk4kafka-c
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 38272
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_AUTOPURGE_SNAPRETAINCOUNT: 5
      ZOOKEEPER_AUTOPURGE_PURGEINTERVAL: 2
      ZOOKEEPER_SERVERS: test-zk4kafka-s:38277:38278 # test-zk4kafka-s:38277:38278
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_JMX_HOSTNAME: test-kafka-s # test-kafka-s
      KAFKA_JMX_PORT: 38279
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "100"
    networks:
      - "test-n"
    ports:
      - "38272:38272"
      - "38277:38277"
      - "38278:38278"
      - "38279:38279"
    volumes:
      - zk4kafka-data-v:/var/lib/zookeeper/data
      - zk4kafka-log-v:/var/lib/zookeeper/log

volumes:
  meta-alert-postgres-data-v:
  meta-alert-postgres-data-test-v:
  kafka-data-v:
  zk4kafka-log-v:
  zk4kafka-data-v:

networks:
  test-n:
    external: true
